AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  BucketName:
    Type: String
    Description: Bucket to monitor and calculate sums for
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - !GetAtt FunctionRole.Arn
          Action:
          - s3:PutObjectAcl
          Resource: !Sub arn:aws:s3:::${Bucket}/*
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python3.6
      CodeUri: lambda.zip
      Events:
        S3:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events:
            - s3:ObjectCreated:*
            - s3:ObjectRemoved:*
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref BucketName
Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref Bucket
  Website:
    Description: S3 website URL
    Value: !GetAtt Bucket.WebsiteURL
